# -*- coding: utf-8 -*-
"""KMeans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HPthBZ8ASb1WrH856fESFdhk2Q1fZsKp
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset=pd.read_csv('Mall_Customers.csv')

X=dataset.iloc[:,3:5].values

X

from sklearn.cluster import KMeans
  wcss=[]
  for i in range(1,11):
    kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)
  plt.plot(range(1,11),wcss)
  plt.title('Elbow method')
  plt.xlabel('Number of clusters')
  plt.ylabel('WCSS')

kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)

y_kmeans=kmeans.fit_predict(X)
print(y_kmeans)

plt.scatter(X[y_kmeans==0,0],X[y_kmeans==0,1],s=100,c='red',label='c1')
plt.scatter(X[y_kmeans==1,0],X[y_kmeans==1,1],s=100,c='blue',label='c2')
plt.scatter(X[y_kmeans==2,0],X[y_kmeans==2,1],s=100,c='yellow',label='c3')
plt.scatter(X[y_kmeans==3,0],X[y_kmeans==3,1],s=100,c='green',label='c4')
plt.scatter(X[y_kmeans==4,0],X[y_kmeans==4,1],s=100,c='orange',label='c5')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=300,c='magenta',label='centre')
plt.legend()

