# -*- coding: utf-8 -*-
"""Polynomial Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TuchUkPp62vYrWCyU47dX2hs84RnjMQ9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset=pd.read_csv('Position_Salaries.csv')

X=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

y

X

from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(X,y)

from sklearn.preprocessing import PolynomialFeatures
poly_reg=PolynomialFeatures(degree=4)
x_poly = poly_reg.fit_transform(X)
lin_reg_2=LinearRegression()
lin_reg_2.fit(x_poly,y)

plt.scatter(X,y,color='red')
plt.plot(X,lin_reg.predict(X),color='blue')
plt.title('Truth or bluff')
plt.xlabel('Levels')
plt.ylabel('Salaries')
plt.show()

plt.scatter(X,y,color='red')
plt.plot(X,lin_reg_2.predict(poly_reg.fit_transform(X)),color='blue')
plt.title('New Truth or bluff')
plt.xlabel('Position levels')
plt.ylabel('Salaries')

X_grid=np.arange(min(X),max(X),0.1)
X_grid=X_grid.reshape(len(X_grid),1)
plt.scatter(X,y,color='red')
plt.plot(X_grid,lin_reg_2.predict(poly_reg.fit_transform(X_grid)),color='blue')
plt.title('New Truth or bluff')
plt.xlabel('Position levels')
plt.ylabel('Salaries')

lin_reg.predict([[6.5]])

lin_reg_2.predict(poly_reg.fit_transform([[6.5]]))

print