# -*- coding: utf-8 -*-
"""Support vector regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1enQWBs0UPiplajxjzQrNbOSB8NgFxn4N
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset=pd.read_csv('Position_Salaries.csv')

X=dataset.iloc[:,1:-1]
y=dataset.iloc[:,-1]

print(X)
print(y)

y=np.array(y)

print(y)

X=np.array(X)

print(X)

y=y.reshape(len(y),1)

print(y)

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
X=sc.fit_transform(X)
sc_y=StandardScaler()
y=sc_y.fit_transform(y)

print(X)

print(y)

from sklearn.svm import SVR
regressor=SVR(kernel='rbf')
regressor.fit(X,y)

sc_y.inverse_transform(regressor.predict(sc.transform([[6.5]])).reshape(-1,1))

plt.scatter(sc.inverse_transform(X),sc_y.inverse_transform(y),color='red')
plt.plot(sc.inverse_transform(X),sc_y.inverse_transform(regressor.predict(X).reshape(-1,1)))

X_grid=np.arange(min(sc.inverse_transform(X)),max(sc.inverse_transform(X)),0.1)
X_grid=X_grid.reshape(len(X_grid),1)
plt.scatter(sc.inverse_transform(X),sc_y.inverse_transform(y),color='red')
plt.plot(X_grid,sc_y.inverse_transform(regressor.predict(sc.transform(X_grid)).reshape(-1,1)))

